# -*- coding: utf-8 -*-
"""Hangman 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdxbFBZBksujCH_b-3n3WQLgk24aaAEC
"""

import random

class Hangman:
    def __init__(self):
        self.wordlist = ["apple", "banana", "cherry", "dog", "elephant"]
        self.word = random.choice(self.wordlist)
        self.progress = ["?"] * len(self.word)
        self.remaining_guesses = 6

    def print_progress(self):
        print("Word:", " ".join(self.progress))
        print("Remaining guesses:", self.remaining_guesses)

    def guess(self, letter):
        if letter in self.word:
            for i in range(len(self.word)):
                if self.word[i] == letter:
                    self.progress[i] = letter
        else:
            self.remaining_guesses -= 1

    def is_game_over(self):
        return self.remaining_guesses == 0 or all(letter != "?" for letter in self.progress)

    def play(self):
        while not self.is_game_over():
            self.print_progress()
            guess = input("Guess a letter: ")
            self.guess(guess)

        if all(letter != "?" for letter in self.progress):
            print("You win! The word is:", self.word)
        else:
            print("You lose! The word was:", self.word)

if __name__ == "__main__":
    game = Hangman()
    game.play()